title: DrippiGG Documentation
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

navigation:
  - title: "Home"
    url: "/"
  - title: "Documentation"
    url: "/documentation/nixos-digitalocean/"
  - title: "Contributing"
    url: "/contributing/contribution"
